{
    "main": [
        "pytest.mark.asyncio"
    ],
    "test_conn_retry_sync_function": [
        "test_conn_retry_sync_function.test_function",
        "<builtin>.str",
        "backend.util.retry.conn_retry",
        "pytest.raises"
    ],
    "test_conn_retry_sync_function.test_function": [
        "<builtin>.ValueError"
    ],
    "test_conn_retry_async_function": [
        "<builtin>.str",
        "backend.util.retry.conn_retry",
        "test_conn_retry_async_function.test_function",
        "pytest.raises"
    ],
    "test_conn_retry_async_function.test_function": [
        "asyncio.sleep",
        "<builtin>.ValueError"
    ]
}